// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiq9FvgFH0dQDXhvfG6Qkjga6nwrTSCns',
    appId: '1:502896404495:web:3be12a0015d0675f9f5b7a',
    messagingSenderId: '502896404495',
    projectId: 'leafcare-ai-31866',
    authDomain: 'leafcare-ai-31866.firebaseapp.com',
    storageBucket: 'leafcare-ai-31866.firebasestorage.app',
    measurementId: 'G-8XDNFZ5MMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNYJ-G5tPi6yVds0VleRIQYPDNsl2_RQs',
    appId: '1:502896404495:android:65f910bbceb0dcbc9f5b7a',
    messagingSenderId: '502896404495',
    projectId: 'leafcare-ai-31866',
    storageBucket: 'leafcare-ai-31866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9I2k7TU5EntnRiRNeF7jMy2osu0ldys',
    appId: '1:502896404495:ios:06803d33959e2eae9f5b7a',
    messagingSenderId: '502896404495',
    projectId: 'leafcare-ai-31866',
    storageBucket: 'leafcare-ai-31866.firebasestorage.app',
    iosBundleId: 'com.example.leafcareAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9I2k7TU5EntnRiRNeF7jMy2osu0ldys',
    appId: '1:502896404495:ios:06803d33959e2eae9f5b7a',
    messagingSenderId: '502896404495',
    projectId: 'leafcare-ai-31866',
    storageBucket: 'leafcare-ai-31866.firebasestorage.app',
    iosBundleId: 'com.example.leafcareAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiq9FvgFH0dQDXhvfG6Qkjga6nwrTSCns',
    appId: '1:502896404495:web:2b3f218bc931aabb9f5b7a',
    messagingSenderId: '502896404495',
    projectId: 'leafcare-ai-31866',
    authDomain: 'leafcare-ai-31866.firebaseapp.com',
    storageBucket: 'leafcare-ai-31866.firebasestorage.app',
    measurementId: 'G-Q9KDZH52XL',
  );
}
